### ISSUE TITLE
nr_gpus

### ISSUE THREAD

**Issue by shriphani** [openai/pixel-cnn#6]
What's the fewest number of GPUs you can get away with? I have access to 2 and I keep getting OOM errors (I tried batch-sizes 32 and 16). The default value for this param seems to be 8. Are you guys using 8 or have you been able to make it work with fewer?

Best,
Shriphani

**Comment by greaber** [comment]
I don't think the number of GPUs matters except that having more will make the training faster.  GPU memory could matter, but I have tried training on GPUs with only 8GB, and it works fine.  Do you just mean these warnings like the following?

```
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 3.35GiB. The caller indicates that this is not a failure, but may mean that there could be
performance gains if more memory is available.
```
I got these, and I thought maybe the training wasn't working at first, but it turned out I just had to be patient.

**Comment by Kaustubh-Sable** [comment]
@shriphani , the number of GPUs is not a problem. Though, the GPU memory can be a factor. I have executed the model with a single Quadro M6000 24GB GPU and it works perfect. As @greaber said, we need to be a bit patient for the result.

**Comment by shriphani** [comment]
Sorry I didn't follow up - yeah it is a matter of patience.
